apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: global-cluster-secrets
  namespace: flux-system
spec:
  # Self-hosted Infisical URL
  hostAPI: https://infisical.datakube.org/api
  
  # Resync frequency (seconds)
  resyncInterval: 60
  
  # Authentication & Scope
  authentication:
    universalAuth:
      credentialsRef:
        secretName: infisical-credentials
        secretNamespace: flux-system
      secretsScope:
        projectSlug: "talos-8-r-ud"
        envSlug: "prod"
        secretsPath: "/"

  # Target Secret in Kubernetes
  managedSecretReference:
    secretName: cluster-global-env
    secretNamespace: flux-system
    creationPolicy: Owner
