---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: proxmox-csi-credentials
  namespace: flux-system
spec:
  hostAPI: https://infisicial.datakube.org/api
  resyncInterval: 60
  authentication:
    universalAuth:
      credentialsRef:
        secretName: infisical-credentials
        secretNamespace: flux-system
      secretsScope:
        projectSlug: "talos-8-r-ud"
        envSlug: "prod"
        secretsPath: "/proxmox" 

  managedSecretReference:
    secretName: csi-proxmox-proxmox-csi-plugin
    secretNamespace: csi-proxmox
    creationPolicy: Owner
